### PR TITLE
Store the parent RealizedElement for each cell in the cell itself

### PR DESCRIPTION
**Pull request by adly-holler**
@joshaber

### CODE REVIEW

**Comment by joshaber** [comment]
Hmm, it looks like this would have the same retain cycle problem that we had a while back. Once `parentElement` has been created, it keep a strong reference to `self`, while `self` also has a strong reference to `parentElement`.

**Comment by adly-holler** [comment]
OK that's true for the Mac one, but not for the iOS one, since iOS uses a separate `contentView`. I could either revert the Mac-side changes, or create a subview that fills the cell and use that as the root view. What do you think @joshaber ?

**Comment by joshaber** [comment]
>I could either revert the Mac-side changes

Let's just do that for now :+1:

**Comment by adly-holler** [comment]
Done @joshaber

**Comment by joshaber** [comment]
:metal:

**Pull request merged**
