### PR TITLE
Fix iOS demo build

### PR DESCRIPTION
**Pull request by adly-holler**
@joshaber

### CODE REVIEW

**Comment by joshaber** [comment]
I wonder if we should have a `Button.init` for that simple case?

**Comment by adly-holler** [comment]
I leave that to your judgment. In real apps you'll almost never use that default font/color and you'll have images in a lot of cases, so I feel like the convenience init would either be uselessly simple (outside of the demo) or pointlessly close to the regular init.

**Comment by adly-holler** [comment]
Actually never mind, it might be a little baffling to new users so I'll do it. one sec

**Comment by adly-holler** [comment]
@joshaber

**Comment by joshaber** [comment]
:metal:

**Pull request merged**
