### PR TITLE
don't crash when realizing an autofocus element outside a window

### PR DESCRIPTION
**Pull request by adly-holler**
Sometimes you gotta realize an element outside the window hierarchy. In iOS for example, `UIViewController.viewDidLoad` is called before the view is added to a window but setting a subview to first responder still works. Probably due to some hackery on Apple's part.

### CODE REVIEW

**Comment by joshaber** [comment]
I *think* we should still use force-unwrapping for OS X because if `window`s `nil` then `autofocus` isn't gonna work. I *think*.

**Comment by adly-holler** [comment]
Yeah if we do, then there's a disparity between platforms because it could fail silently in pathological cases on iOS. If we don't, it may fail silently in common cases on Mac. You're the boss, and you're the Mac man, so one sec

**Comment by joshaber** [comment]
>Yeah if we do, then there's a disparity between platforms because it could fail silently in pathological cases on iOS.

Yup :cry: I'd love to know if/when we find those cases on iOS. I didn't even realize iOS behaved that way.

**Comment by joshaber** [comment]
:cool:

**Pull request merged**
