### PR TITLE
Simpler Component, better layout

### PR DESCRIPTION
**Pull request by joshaber**
This started as an attempt at making layout more holistic, but it also has the nice benefit of making `Component` much simpler.

### CODE REVIEW

**Comment by coenert** [comment]
Looks good, this makes `Component` a lot simpler. I also thought about moving the rendering outside `Component` inside something like a `RootView`. Because then we maybe can switch to something like a protocol for Components or Elements.

**Comment by joshaber** [comment]
>I also thought about moving the rendering outside `Component` inside something like a `RootView`. Because then we maybe can switch to something like a protocol for Components or Elements.

Yup, I'd love to do that. I thought about heading that road in this PR but decided the scope was already too big :see_no_evil:

**Comment by joshaber** [comment]
I also ended up burning down `ScrollView` because it's pretty superfluous with `TableView` existing.

**Pull request merged**
