### PR TITLE
Swift 2.0 - Xcode 7 Beta 5 (Because I have nothing better to do on a Saturday night)

### PR DESCRIPTION
**Pull request by joshdholtz**
:warning: :warning: DON'T MERGE YET :warning: :warning:

:warning: :warning: SUPER DON'T MERGE YET :warning: :warning: 

I've been wanting to start a new Swift 2 project and wanted to use Few. So I took some time tonight to **try** converting everything over. I have no idea if _everything_ works but things compile and both the Mac and iOS schemes build and run

PS - You probably shouldn't merge this yet (especially not into master)

### CODE REVIEW

**Comment by mikker** [comment]
Shouldn't the `Carthage/Checkouts` files be ignored?

**Comment by joshdholtz** [comment]
@mikker Yes, they probably should 😇 I assumed that was in the `gitignore` already but I guess it's not. I will remove those 👌

**Comment by joshdholtz** [comment]
Since it looked like none of the Carthage directory was commit before, I added the ignore to the whole Carthage directory. Now this PR looks a bit more manageable 😉

**Comment by joshaber** [comment]
Awesome, thanks!

Could you target the `swift-2` branch instead of `master`?

**Comment by joshdholtz** [comment]
@joshaber You got it :ok_hand:

**Comment by joshdholtz** [comment]
Closing because of #96

**Pull request closed without merging**
