### PR TITLE
Make Button a lot more flexible

### PR DESCRIPTION
**Pull request by adly-holler**
@joshaber

### CODE REVIEW

**Comment by joshaber** [comment]
So this is interesting. Part of me isn't sure this fits philosophically.

Ideally a component's `render` function is of type `State -> Element`, but using buttons with this API makes it more like `State -> (ButtonState -> Element)`, which is conceptually less clear. Ideally the button's state would be reified so that each time one of the control states changes, it'd be re-rendered with the appropriate properties.

The other side of this is pragmatism: we're mapping a different concept on to an existing UI framework and sometimes that's gonna bleed through.

Does that make sense? What do you think?

**Comment by adly-holler** [comment]
OK interesting. You're thinking, say, `Button` would actually have an immutable `controlState` property? I totally like that idea.

**Comment by adly-holler** [comment]
That said, these state changes are also triggered by the button itself. For example, the Highlighted state is automatically set/cleared on touchdown/touchup. Hmm…

OK, we definitely need access to the disabled state. Let me cook something up

**Comment by joshaber** [comment]
Hmm yeah.

What if we go with your original proposal but used dictionaries instead of functions? E.g.:

```swift
public var attributedTitle: [UIControlState: NSAttributedString]
```

**Comment by adly-holler** [comment]
@joshaber How bout this?

**Comment by joshaber** [comment]
:metal:

**Pull request merged**
